### ISSUE TITLE
Model Catalog Abstract and main item updates pre-NTK blog post

### ISSUE THREAD

**Issue by hsu000001** [usgs-biolab/pymodelcat#3]
In preparation for a NTK blog post, the link to the model catalog will be released soon. This issue is for anyone to note things that should be changed so that they can be gathered into one / a few pull requests before that blog is released.

Here are a few things to start with:
1. The disclaimer says that this is a catalog not a repository, but the first sentence now says "This repository," so that should probably be changed to "This catalog."
2. We can link to the following: (a) wiki page with background/motivation, (b) distinctions between catalog/repository, (c) definition of model as we are starting it, (d) this github repo for feedback, (e) included in this repo, list of labels for refining/comment, (f) possibly a public version of the blog post, which sets the context, (g) I would be interested in a github.io/blog-like thing to post short explanations of the decisions we made. This could also be done on the Confluence wiki if needed.
3. Amanda and Grace are working on finding an overview image, and emphasizing 5-10 "more fully populated" model pages/front page.

**Comment by skybristol** [comment]
I like the idea of using this repo as a rallying point for public facing documentation/notes on the process of developing the model catalog idea. We could certainly use GitHub pages or the wiki feature to house reference content as needed. We could also use the GitHub Projects feature to track tasks. To me, "decision points" lend themselves to tracking in issue conversation and resolution.

I'm willing to try anything, but with all of the projects I'm involved in moving to more asynchronous online tracking mechanisms, I've been working in just about every platform (MS Teams, Slack, Trello, etc.) on ways of communicating and tracking progress on projects. I'm more and more a fan of trying to keep things somewhat simple and not introducing new features in a project to navigate through until they really become obviously necessary.

I think we're going to want to use issues here regardless, so perhaps we can just stick with getting our usage of issue tracking a bit more structured and refined and then decide if/when we need to put another tool into play. I'll make an attempt to set some patterns with some of what you list here.

**Comment by hsu000001** [comment]
I like the version that is in the .md file now. I am going to add a link to the Confluence page with more info in a pull request. After that is accepted or not, I would like to copy/paste the .md file content to the ScienceBase item and close this issue.

**Comment by skybristol** [comment]
Note the console script that I added to the pymodelcat package that handles the synchronization of the md file in the repo with the ScienceBase collection item.
