### ISSUE TITLE
More information in Contributing.md

### ISSUE THREAD

**Issue by hsu000001** [usgs-biolab/pymodelcat#8]
Could someone please add more information to Contributing.md in the section "Using GitHub (doesn't require knowing Git)" about whether branches or forks should be deleted after merges occur. I'm not sure how to request a 2nd change since my fork already exists but is behind, but there are scary warning messages about deleting forks. Newbie.

**Comment by skybristol** [comment]
Branches can be deleted in your local fork once they have served their purpose - contain a set of logically grouped changes and been merged up into the main branch. Deleting them can help you keep "clutter" down in a fork. You shouldn't delete your fork unless you are completely done contributing and no longer care to maintain it. I'll take a look at the contributing page and see what needs to be added/tweaked.

**Comment by TrashBirdEcology** [comment]
@hsu000001, you'll need to set the upstream on your fork and regularly update if you want to stay UTD with the usgs-biolab. 
Here are some resources:
https://help.github.com/en/github/getting-started-with-github/fork-a-repo
https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date

The alternative to syncing your fork with the upstream is the opposite of what @skybristol suggested -- de-fork  and then re-fork or clone it every time you want to PR some contribution...but as @skybristol mentioned, definitely don't de-fork that unless you're no longer interested in contributing, or receiving credit for the contributions. 

When you de-fork, however, there's a [risk of losing some information associated with your contributions](https://softwareengineering.stackexchange.com/questions/61577/should-i-keep-my-github-forked-repositories-around-forever), but I think this is mostly restricted to the PRs showing from which branch/fork it originated.  

Happy to do a screenshare later to try to problem solve, @hsu000001

**Comment by hsu000001** [comment]
I have synced (cloned?) to GitHub Desktop. I think that maybe this will help things. Maybe.
